Feat/sc 16 all cities cat charts
govau/smart-cities pull request #34
Opened 2017-10-16 23:21 UTC by micapam

Jira: <https://govausites.atlassian.net/browse/SC-16>

Preview: <http://smart-cities-sc-16.apps.staging.digital.gov.au>

2017-10-16 23:25 UTC, micapam commented on src/components/AllCitiesCategoryContainer/AllCitiesCategory/AllCitiesCategory.js
> +      {isHeroInSubCategory || <div className={style.heroWrapper}>
This hero chart might be redundant, not 100% sure if hero charts will always be in a subcategory, yet. Once data task is done we might want to get rid of this bit.

2017-10-16 23:25 UTC, micapam commented on src/components/CityColumnChart/CityColumnChart.js
> +    name: INDICATORS[indicatorId].shortDescription,
Not 100% sure on this either (whether to use short description or name) - will need to review once we have the data sorted and can see what needs to be done.

2017-10-16 23:27 UTC, micapam commented on src/constants/categories.js
> +        summaryIndicatorIds: [
Changed the structure of this file so that summary indicators are decoupled from charts. Also, charts can render with one or more indicators.

2017-10-16 23:27 UTC, micapam commented on src/constants/indicators.js
> -  jobsWalk: {
Some of the indicators previously added are no longer present in the 'master' data file.

2017-10-16 23:28 UTC, micapam commented on src/style/_colors.scss
> +  GRID: $color-grid;
This variable was missing, which is why the charts had no horizontal grid lines showing.

2017-10-16 23:28 UTC, micapam commented on src/style/_icons.scss
> +@mixin iconWrapper {
Consolidated this stuff with a view to implementing properly when we do icon system (and to DRY up the placeholder code)

2017-10-17 03:57 UTC, davidgilbertson requested changes
Back to you

2017-10-17 03:57 UTC, davidgilbertson commented on src/components/AllCitiesCategoryContainer/AllCitiesCategory/AllCitiesCategory.js
> +      {isHeroInSubCategory || <div className={style.heroWrapper}>
Minor: for consistency/readability you can start the DOM on the next line:
```jsx
{isHeroInSubCategory || (
  <div className={style.heroWrapper}>
    <CityColumnChart
      cities={props.cities}
      colorBase={props.category.colorName}
      colorVariation="500"
      indicatorIds={[props.category.heroIndicatorId]}
    />
  </div>
)}
```

2017-10-17 03:57 UTC, davidgilbertson commented on src/components/AllCitiesCategoryContainer/AllCitiesCategory/AllCitiesCategory.js
> +    flatten(sc.charts.map(chart => chart.indicatorIds)).includes(props.category.heroIndicatorId)
Minor: this is a bit difficult to decipher. It might be more readable broken up.

Also, to 'cast' to boolean you would normally do `!!`, unless you want to explicitly discount `null`, `false`, etc (which you don't in this case, since it can only return an object or undefined). Also minor, I prefer full words in variable names (rather than `sc`), but that's not a rule anywhere, so...

E.g.
```js
  const isHeroInSubCategory = !!props.category.subCategories.find((subCategory) => {
    const indicatorsFromAllCharts = flatten(subCategory.charts.map(chart => chart.indicatorIds));

    return indicatorsFromAllCharts.includes(props.category.heroIndicatorId);
  });
```

Also, pretty minor, you could do this with native JS `.reduce()` instead of `flatten` removing the need to look up what `flatten` does in order to understand what the code does.

2017-10-17 03:57 UTC, davidgilbertson commented on src/components/SubCategoryDetails/SubCategoryDetails.js
> +const SubCategoryDetails = (props) => {
Minor: if this just shows charts, `<SubCategoryCharts>`?

2017-10-17 03:57 UTC, davidgilbertson commented on src/components/CityColumnChart/CityColumnChart.js
> +              },
Much better :)

2017-10-17 03:57 UTC, davidgilbertson commented on src/components/SubCategoryDetails/SubCategoryDetails.js
> +  const sc = props.subCategory;
We should probably standardise on whether to initialise variable names or not. It isn't done elsewhere in smart-cities, but is done in ICT. My preference is to keep the same name everywhere, so if the prop name is `subCategory` in one place, it is always `subCategory`.

Thoughts?

2017-10-17 03:57 UTC, davidgilbertson commented on src/components/SubCategoryDetails/SubCategoryDetails.js
> +    !chart.indicatorIds.includes(props.heroIndicatorId)));
Minor, prefer closing brace on new line:
```js
  const heroChart = sc.charts.find(chart => (
    chart.indicatorIds.includes(props.heroIndicatorId)),
  );

  const otherCharts = sc.charts.filter(chart => (
    !chart.indicatorIds.includes(props.heroIndicatorId)),
  );
```

2017-10-17 03:57 UTC, davidgilbertson commented on src/components/SubCategoryDetails/SubCategoryDetails.js
> +        <h3 className={style.title}>{sc.name}</h3>
If this is `<h3>` chart title should be `<h4>` now.

2017-10-17 03:57 UTC, davidgilbertson commented on src/components/SubCategoryDetails/SubCategoryDetails.js
> +        {heroChart && <div className={style.heroChartWrapper} key="hero">
Minor, DOM starting on new line to keep indenting looking good.

2017-10-17 03:57 UTC, davidgilbertson commented on src/components/SubCategoryDetails/SubCategoryDetails.js
> +        <h3 className={style.title}>{sc.name}</h3>
`.title` hasn't been defined anywhere, this doesn't match the designs

2017-10-17 03:57 UTC, davidgilbertson commented on src/components/SubCategoryDetails/SubCategoryDetails.js
> +    tint: PropTypes.string.isRequired,
Is tint used anywhere?

2017-10-17 03:57 UTC, davidgilbertson commented on src/components/AllCitiesCategoryContainer/AllCitiesCategory/AllCitiesCategory.js
> +      </div>}
The font size and spacing look wrong (between the 'Infrastructure' row and the chart title), they don't match the designs:
![image](https://user-images.githubusercontent.com/4443482/31644278-2027a0da-b341-11e7-9af7-7107b3939c79.png)

We'd need a different title style for hero charts, right? And different spacing at the top?

2017-10-17 03:57 UTC, davidgilbertson commented on src/components/SubCategoryDetails/SubCategoryDetails.scss
> +}
Unless I'm missing something, there's no need for `flex-basis` here, all you want to do is set the width, right? (`flex-basis` defaults to `auto` which just resolves to the `width`. Interestingly, the spec actually recommends against using flex-basis directly.)

Also you can do 50% not 49%.

Also, if you're setting, then overriding a value, prefer 'mobile first'.

You can do:
```scss
.chartWrapper {
  width: 100%;

  @include for-tablet-portrait-up {
    width: 50%;
  }
}

.heroChartWrapper {
  width: 100%;
}
```

Also, the axis labels are cut off (very neatly). See 0%, 5%, 0%, 5% in the screenshot.

2017-10-17 03:57 UTC, davidgilbertson commented on src/components/SubCategoryDetails/SubCategoryDetails.scss
> +  flex-direction: column;
You don't need flex here, the children are all just block level elements going down the page.
Setting these three have no effect, so can be removed:
```css
display: flex;
flex-direction: column;
width: 100%;
```

2017-10-17 03:57 UTC, davidgilbertson commented on src/components/SubCategoryDetails/SubCategoryDetails.scss
> +  width: 100%;
Is there a reason for `width: 100%`? Anything with a display of `block` or `flex` will be a 'block-level' element which will take all available width.

Unless there's a browser quirk I'm missing.

2017-10-17 03:57 UTC, davidgilbertson commented on src/components/SubCategoryDetails/SubCategoryDetails.scss
> +  width: 100%;
`width: 100%` can go

2017-10-17 03:57 UTC, davidgilbertson commented on src/components/SubCategoryDetails/SubCategoryDetails.scss
> +}
The layout here looks a bit funky when one chart has a legend. Also the title is indented in quite a way and looks strange. Also I wanted to do something with big red arrows.
![image](https://user-images.githubusercontent.com/4443482/31645201-7e4ef1fe-b346-11e7-8181-3e458bc85d3f.png)

2017-10-17 03:57 UTC, davidgilbertson commented on src/components/SubCategorySummary/SubCategorySummary.scss
> +  @include iconWrapper;
yeah, nice.

2017-10-17 03:57 UTC, davidgilbertson commented on src/constants/categories.js
> +            ],
This needs a mechanism to feed through the text that goes in the tooltip (`longDescription`). If you do this here:
```js
{
  name: 'Participation rate',
  longDescription: 'This is the text that will show in the tooltip for this chart',
  indicatorIds: [
    'participationRateGeneral',
    'participationRateFemale',
    'participationRateMale',
  ],
},
```

And then in `<SubCategoryDetails>` and wherever else you render the chart you do this:
```jsx
<CityColumnChart
  title={chart.name}
  longDescription={chart.longDescription}
  cities={props.cities}
  colorBase={props.colorName}
  colorVariation={sc.shade}
  indicatorIds={chart.indicatorIds}
/>
```

2017-10-17 03:57 UTC, davidgilbertson commented on src/components/SubCategoryDetails/SubCategoryDetails.js
> +      key={sc.name}
`key` can go. It's only needed inside a loop (where it's in the actual context of the array, you don't need it if a component was originally rendered as the output of a loop, if that makes sense)

2017-10-17 03:57 UTC, davidgilbertson commented on src/components/SubCategoryDetails/SubCategoryDetails.scss
> +@import '~style/variables';
I have a bunch of comments below, all adding up to this as the final CSS (assuming a new `<div className={style.wrapper}>` at the top of `<SubCategoryDetails>`).
```scss
.wrapper {
  background: $color-white;
  padding-top: 32px;
  margin-bottom: 16px;
}

.container {
  @include container;
}

.heading {
  display: flex;
  align-items: center;
  margin-bottom: 16px;
}

.chartGrid {
  display: flex;
  flex-flow: row wrap;
}

.chartWrapper {
  width: 100%;

  @include for-tablet-portrait-up {
    width: 50%;
  }
}

.heroChartWrapper {
  width: 100%;
}

.iconWrapper {
  @include iconWrapper;
}
```

2017-10-17 03:57 UTC, davidgilbertson commented on src/components/SubCategoryDetails/SubCategoryDetails.scss
> +.container {
The charts fill the full width of the page. I believe everything should be contained to be max 1140px. I could be wrong though.

2017-10-17 03:57 UTC, davidgilbertson commented on src/components/SubCategoryDetails/SubCategoryDetails.scss
> +.container {
You'd need to do this in here and for the hero chart.

2017-10-17 03:57 UTC, davidgilbertson commented on src/components/SubCategoryDetails/SubCategoryDetails.js
> +        {heroChart && <div className={style.heroChartWrapper} key="hero">
And `key="hero"` can go, key is only needed directly inside a loop.

2017-10-17 04:06 UTC, micapam commented on src/components/AllCitiesCategoryContainer/AllCitiesCategory/AllCitiesCategory.js
> +      {isHeroInSubCategory || <div className={style.heroWrapper}>
Oh yep, that is nicer.

2017-10-17 05:20 UTC, micapam commented on src/components/SubCategoryDetails/SubCategoryDetails.js
> +    tint: PropTypes.string.isRequired,
I think this is hangover from original copy-paste from sub cat summary

2017-10-19 22:42 UTC, micapam commented on src/components/AllCitiesCategoryContainer/AllCitiesCategory/AllCitiesCategory.js
> +      </div>}
I needed to tweak the styling, but the title style is no different for hero charts as far as I can see: https://projects.invisionapp.com/d/main#/console/11859769/257007528/inspect

2017-10-20 00:33 UTC, merged