Feat/sc 78 context page
govau/smart-cities pull request #36
Opened 2017-10-18 05:15 UTC by davidgilbertson

Jira: https://govausites.atlassian.net/browse/SC-78

This adds 'context' as a new category. The context page is special in a few ways. Each 'sub category' background colour isn't just a different tint of the base colour, it's a specific shade from another category. So I've refactored the code to use explicit colours rather than define only the shade/tint.

I could rip the whole `colorName` thing out, since it always matches the ID, but this would probably cause nasty conflicts with SC-16 so I'll do it later.

Desktop:
![image](https://user-images.githubusercontent.com/4443482/31701891-1a4d98d4-b41f-11e7-8e12-2baf2e6bf790.png)

2017-10-18 05:23 UTC, davidgilbertson commented on src/components/SubCategorySummary/SubCategorySummary.scss
> +  border-top: 4px solid $color-white;
No strictly related, but added the little white gap that was added to the designs at some point.

2017-10-20 02:01 UTC, micapam requested changes
Not sure what's causing this, but I notice that, in desktop view (n.b. on my small laptop, its screen seems to be - or emulate, since it's retina - 1275px in width), when I'm looking at a category, I can't see the 'Overview' button any more in the category nav - it gets tucked away behind the cities nav. It may well be this is not a new bug per se but just something that has been exposed by the change in elements on the screen:

![image](https://user-images.githubusercontent.com/165087/31801727-dbee450c-b595-11e7-82a1-aa91a7104eda.png)

Also, in mobile view, if I'm on a category midway through the list, so that the category nav scrolls to position, I can't see the little edge of the button off to the left any more, to show me that there are other categories offscreen ...

<img width="361" alt="missing_button" src="https://user-images.githubusercontent.com/165087/31801860-8b445aa0-b596-11e7-8f24-85e66786b85e.png">

2017-10-20 02:01 UTC, micapam commented on src/components/PageBanner/PageBanner.js
> +        {!props.isContextPage && (
Ah is this the usual syntax? I had assumed `boolean || <markup />`

2017-10-20 03:08 UTC, davidgilbertson commented on src/components/PageBanner/PageBanner.js
> +        {!props.isContextPage && (
I've only ever seen the && syntax used, so it reads more like an `if`. When I saw your `||` I almost commented but figured it doesn't really make any difference.

2017-10-20 03:29 UTC, davidgilbertson commented
Ah, the nav items were too wide for the screen at just over 1200px. So when you clicked a category, they would get scrolled to the right a bit and the left one hidden. I've fixed that with slightly smaller spacing for desktop, then large again for 'big desktop' (1440px+)

There was a second problem of padding on the left which I introduced last week some time. I've fixed that too.

The width at 1200px now:

![image](https://user-images.githubusercontent.com/4443482/31804096-f1c91390-b5a2-11e7-893f-51760d35abd1.png)

2017-10-20 04:22 UTC, micapam approved these changes

2017-10-20 04:22 UTC, micapam commented
Mobile & desktop views both look good now. lgtm

2017-10-20 04:37 UTC, merged