City nav links should point to overview
govau/smart-cities pull request #78
Opened 2017-11-17 03:30 UTC by micapam

2017-11-20 02:16 UTC, davidgilbertson requested changes
_This_ should have some vestigial code removed.

2017-11-20 02:16 UTC, davidgilbertson commented on src/components/CityNavContainer/CityNav/CityNav.js
> +  const locationHasCity = (location, city) => location && location.pathname.startsWith(`/${city}/`);
Technically this would throw if `location.pathname` was undefined.

2017-11-20 02:16 UTC, davidgilbertson commented on src/components/SideBar/SideBar.js
> -          categoryId={props.categoryId}
`categoryId` can go from propTypes in this file, and removed from `SideBar.test.js` and no longer needs to be passed down to `<SideBar>` from `<PageWrapper>`.

Also, the comment in the line below is a leftover and can go.

2017-11-22 05:12 UTC, micapam commented
back to you @davidgilbertson

2017-11-27 02:54 UTC, davidgilbertson approved these changes
Oops, this dropped off my radar

2017-11-27 05:16 UTC, merged